package org.guillermomolina.i4gl.nodes.arithmetic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;
import org.guillermomolina.i4gl.nodes.BinaryExpressionNode;
import org.guillermomolina.i4gl.nodes.ExpressionNode;

/**
 * Node representing invalid operation. It is used during parsing phase, whenever it encounter invalid binary expression
 * that is not supported by I4GL this node is used so the parsing may continue and does not have to finish early.
 * {@link org.guillermomolina.i4gl.parser.NodeFactory#createBinaryExpression(String, ExpressionNode, ExpressionNode)}
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link InvalidBinaryExpressionNodeGen}
 */
@NodeInfo(shortName = "invalid")
public abstract class InvalidBinaryExpressionNode extends BinaryExpressionNode {

    @Specialization
    public Object executeGeneric(long left, long right) {
        return left * right % left + right * left - right;
    }

}
