package org.guillermomolina.i4gl.nodes.variables.read;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeField;
import com.oracle.truffle.api.dsl.NodeFields;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.instrumentation.StandardTags.ReadVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;

import org.guillermomolina.i4gl.nodes.I4GLExpressionNode;
import org.guillermomolina.i4gl.runtime.types.I4GLType;
import org.guillermomolina.i4gl.runtime.values.I4GLRecord;

/**
 * This node reads value from an record with specified identifier.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link ReadFromRecordNodeGen}
 */
@NodeChild(value = "record", type = I4GLExpressionNode.class)
@NodeFields({
    @NodeField(name = "identifier", type = String.class),
    @NodeField(name = "returnType", type = I4GLType.class)
})
public abstract class I4GLReadFromRecordNode extends I4GLExpressionNode {

    protected abstract I4GLType getReturnType();

    protected abstract String getIdentifier();

    @Specialization(guards = "isInt()")
    int readInt(I4GLRecord record) {
        try {
            return (int)record.get(getIdentifier());
        } catch (NullPointerException|ClassCastException e) {
            return 0;
        }
    }

    @Specialization(guards = "isBigInt()")
    long readBigInt(I4GLRecord record) {
        return (long)record.get(getIdentifier());
    }

    @Specialization(guards = "isSmallFloat()")
    float readSmallFloat(I4GLRecord record) {
        return (float)record.get(getIdentifier());
    }

    @Specialization(guards = "isFloat()")
    double readFloat(I4GLRecord record) {
        return (double)record.get(getIdentifier());
    }

    @Specialization(replaces = { "readInt", "readBigInt", "readSmallFloat", "readFloat" })
    Object readGeneric(I4GLRecord record) {
        return record.get(getIdentifier());
    }

    @Override
    public I4GLType getType() {
        return this.getReturnType();
    }

    @Override
    public boolean hasTag(Class<? extends Tag> tag) {
        return tag == ReadVariableTag.class || super.hasTag(tag);
    }
}
