package org.guillermomolina.i4gl.nodes.variables.read;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeChildren;
import com.oracle.truffle.api.dsl.NodeField;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.instrumentation.StandardTags.ReadVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;

import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.runtime.customvalues.CharValue;
import org.guillermomolina.i4gl.runtime.customvalues.VarcharValue;

/**
 * This nodes read value from an array at specified index.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link ReadFromArrayNodeGen}
 */
@NodeChildren({
        @NodeChild(value = "valueNode", type = ExpressionNode.class),
        @NodeChild(value = "indexNode", type = ExpressionNode.class)
})
@NodeField(name = "returnType", type = TypeDescriptor.class)
public abstract class ReadFromIndexedNode extends ExpressionNode {

    protected abstract TypeDescriptor getReturnType();

    @Specialization
    int readInt(int[] array, int index) {
        return array[index - 1];
    }

    @Specialization
    long readLong(long[] array, int index) {
        return array[index - 1];
    }

    @Specialization
    float readFloat(float[] array, int index) {
        return array[index - 1];
    }

    @Specialization
    double readDouble(double[] array, int index) {
        return array[index - 1];
    }

    @Specialization
    String readString(String string, int index) {
        return Character.toString((string.charAt(index - 1)));
    }

    @Specialization
    String readString(CharValue charValue, int index) {
        return Character.toString(charValue.getCharAt(index - 1));
    }

    @Specialization
    String readString(VarcharValue varchar, int index) {
        return Character.toString(varchar.getCharAt(index - 1));
    }

    @Specialization
    Object readGeneric(Object[] array, int index) {
        return array[index - 1];
    }

    @Override
    public TypeDescriptor getType() {
        return this.getReturnType();
    }

    @Override
    public boolean hasTag(Class<? extends Tag> tag) {
        return tag == ReadVariableTag.class || super.hasTag(tag);
    }

}
