package org.guillermomolina.i4gl.nodes.variables.read;

import com.oracle.truffle.api.dsl.NodeField;
import com.oracle.truffle.api.dsl.NodeFields;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.frame.FrameSlot;
import com.oracle.truffle.api.frame.FrameSlotTypeException;
import com.oracle.truffle.api.frame.VirtualFrame;
import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.runtime.customvalues.Reference;
import org.guillermomolina.i4gl.runtime.exceptions.UnexpectedRuntimeException;
import org.guillermomolina.i4gl.parser.identifierstable.types.TypeDescriptor;

/**
 * This node reads value from a variable passed by reference.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link ReadReferenceVariableNodeGen}
 */
@NodeFields({
    @NodeField(name = "slot", type = FrameSlot.class),
    @NodeField(name = "typeDescriptor", type = TypeDescriptor.class),
})
public abstract class ReadReferenceVariableNode extends ExpressionNode {

	protected abstract FrameSlot getSlot();

	protected abstract TypeDescriptor getTypeDescriptor();

    @Specialization(guards = "isInt()")
    int readIntReference(VirtualFrame frame) {
        try {
            Reference reference = (Reference) frame.getValue(getSlot());
            return reference.getFromFrame().getInt(reference.getFrameSlot());
        } catch (FrameSlotTypeException e) {
            throw new UnexpectedRuntimeException();
        }
    }

    @Specialization(guards = "isLong()")
    long readLongReference(VirtualFrame frame) {
        try {
            Reference reference = (Reference) frame.getValue(getSlot());
            return reference.getFromFrame().getLong(reference.getFrameSlot());
        } catch (FrameSlotTypeException e) {
            throw new UnexpectedRuntimeException();
        }
    }

    @Specialization(guards = "isDouble()")
    double readDoubleReference(VirtualFrame frame) {
        try {
            Reference reference = (Reference) frame.getValue(getSlot());
            return reference.getFromFrame().getDouble(reference.getFrameSlot());
        } catch (FrameSlotTypeException e) {
            throw new UnexpectedRuntimeException();
        }
    }

    @Specialization(guards = "isChar()")
    char readCharReference(VirtualFrame frame) {
        try {
            Reference reference = (Reference) frame.getValue(getSlot());
            return (char) reference.getFromFrame().getByte(reference.getFrameSlot());
        } catch (FrameSlotTypeException e) {
            throw new UnexpectedRuntimeException();
        }
    }

    @Specialization(guards = "isBoolean()")
    boolean readBooleanReference(VirtualFrame frame) {
        try {
            Reference reference = (Reference) frame.getValue(getSlot());
            return reference.getFromFrame().getBoolean(reference.getFrameSlot());
        } catch (FrameSlotTypeException e) {
            throw new UnexpectedRuntimeException();
        }
    }

    @Specialization
    Object readReference(VirtualFrame frame) {
        Reference reference = (Reference) frame.getValue(getSlot());
        return reference.getFromFrame().getValue(reference.getFrameSlot());
    }

	@Override
    public TypeDescriptor getType() {
	    return this.getTypeDescriptor();
    }

}
