package org.guillermomolina.i4gl.nodes.variables.read;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeChildren;
import com.oracle.truffle.api.dsl.NodeField;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.instrumentation.Tag;
import com.oracle.truffle.api.instrumentation.StandardTags.ReadVariableTag;

import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.parser.identifierstable.types.TypeDescriptor;
import org.guillermomolina.i4gl.runtime.customvalues.I4GLString;
import org.guillermomolina.i4gl.runtime.customvalues.NCharValue;
import org.guillermomolina.i4gl.runtime.customvalues.VarcharValue;

/**
 * This nodes read value from an array at specified index.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link ReadFromArrayNodeGen}
 */
@NodeChildren({
        @NodeChild(value = "valueNode", type = ExpressionNode.class),
        @NodeChild(value = "indexNode", type = ExpressionNode.class),
})
@NodeField(name = "returnType", type = TypeDescriptor.class)
public abstract class ReadFromArrayNode extends ExpressionNode {

    protected abstract TypeDescriptor getReturnType();

    @Specialization
    int readInt(int[] array, int index) {
        return array[index - 1];
    }

    @Specialization
    long readLong(long[] array, int index) {
        return array[index - 1];
    }

    @Specialization
    double readDouble(double[] array, int index) {
        return array[index - 1];
    }

    @Specialization
    char readChar(char[] array, int index) {
        return array[index - 1];
    }

    @Specialization
    char readString(I4GLString string, int index) {
        return (char) string.getValueAt(index - 1);
    }

    @Specialization
    char readNChar(NCharValue string, int index) {
        return (char) string.getValueAt(index - 1);
    }

    @Specialization
    char readVarchar(VarcharValue string, int index) {
        return (char) string.getValueAt(index - 1);
    }

    @Specialization
    Object readGeneric(Object[] array, int index) {
        return array[index - 1];
    }

    @Override
    public TypeDescriptor getType() {
        return this.getReturnType();
    }

    @Override
    public boolean hasTag(Class<? extends Tag> tag) {
        return tag == ReadVariableTag.class || super.hasTag(tag);
    }

}
