package com.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.frame.VirtualFrame;

import com.guillermomolina.i4gl.nodes.expression.I4GLExpressionNode;
import com.guillermomolina.i4gl.runtime.types.I4GLType;
import com.guillermomolina.i4gl.runtime.types.compound.I4GLTextType;

/**
 * Node representing string literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link TextLiteralNodeGen}
 */
public final class I4GLTextLiteralNode extends I4GLExpressionNode {

	private final String value;

	public I4GLTextLiteralNode(String value) {
		this.value = value;
	}

    @Override
    public String executeGeneric(VirtualFrame frame) {
        return value;
    }

    @Override
    public I4GLType getType() {
        return I4GLTextType.SINGLETON;
    }

}
