package com.guillermomolina.i4gl.nodes.arithmetic;

import com.oracle.truffle.api.CompilerDirectives.TruffleBoundary;
import com.oracle.truffle.api.dsl.Fallback;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import com.guillermomolina.i4gl.nodes.expression.I4GLBinaryExpressionNode;
import com.guillermomolina.i4gl.runtime.exceptions.I4GLRuntimeException;

/**
 * Node representing subtraction operation. If the arguments are set types, it is understood as set difference.
 *
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link I4GLSubtractNodeGen}
 */
@NodeInfo(shortName = "-")
public abstract class I4GLSubtractNode extends I4GLBinaryExpressionNode {

    @Specialization(rewriteOn = ArithmeticException.class)
    protected int sub(int left, int right) {
        return Math.subtractExact(left, right);
    }

    @Specialization
    @TruffleBoundary
    protected long sub(long left, long right) {
        return Math.subtractExact(left, right);
    }

    @Specialization
    protected float sub(float left, float right) {
        return left - right;
    }

    @Specialization
    @TruffleBoundary
    protected double sub(double left, double right) {
        return left - right;
    }

    @Fallback
    protected Object typeError(Object left, Object right) {
        throw new I4GLRuntimeException("Type error doing: " + left + " - " + right);
    }
}
