package org.guillermomolina.i4gl.nodes.variables.write;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeChildren;
import com.oracle.truffle.api.dsl.Specialization;
import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.nodes.statement.StatementNode;
import org.guillermomolina.i4gl.runtime.customvalues.PointerValue;

/**
 * Node representing assignment to a dereferenced pointer. Compared to {@link SimpleAssignmentNode} it assigns the value
 * to the heap instead of frame.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link AssignToDereferenceNodeGen}
 */
@NodeChildren({
        @NodeChild(value = "pointerNode", type = ExpressionNode.class),
        @NodeChild(value = "valueNode", type = ExpressionNode.class)
})
public abstract class AssignToDereferenceNode extends StatementNode {

    @Specialization
    void assignGeneric(PointerValue pointer, Object value) {
        pointer.setDereferenceValue(value);
    }

}
