package org.guillermomolina.i4gl.nodes.variables.write;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeChildren;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.frame.FrameSlotTypeException;
import com.oracle.truffle.api.instrumentation.StandardTags.WriteVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;

import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.nodes.statement.I4GLStatementNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.runtime.customvalues.NullValue;
import org.guillermomolina.i4gl.runtime.customvalues.RecordValue;
import org.guillermomolina.i4gl.runtime.customvalues.TextValue;
import org.guillermomolina.i4gl.runtime.exceptions.I4GLRuntimeException;
import org.guillermomolina.i4gl.runtime.exceptions.UnexpectedRuntimeException;

/**
 * Node representing assignment to a record. Compared to
 * {@link SimpleAssignmentNode} it assigns the value to the record's frame
 * instead of function's frame.
 *
 * This node uses specializations which means that it is not used directly but
 * completed node is generated by Truffle. {@link AssignToRecordFieldNodeGen}
 */
@NodeChildren({ @NodeChild(value = "recordNode", type = ExpressionNode.class),
        @NodeChild(value = "indexNode", type = ExpressionNode.class),
        @NodeChild(value = "valueNode", type = ExpressionNode.class) })
public abstract class AssignToRecordTextNode extends I4GLStatementNode {

    private final String identifier;
    private final TypeDescriptor descriptor;

    AssignToRecordTextNode(String identifier, TypeDescriptor descriptor) {
        this.identifier = identifier;
        this.descriptor = descriptor;
    }

    @Specialization
    void assignText(RecordValue record, int index, TextValue value) {
        try {
            Object targetObject = record.getFrame().getObject(record.getSlot(this.identifier));
            if (targetObject instanceof NullValue) {
                targetObject = descriptor.getDefaultValue();
                record.getFrame().setObject(record.getSlot(this.identifier), targetObject);
            }

            if (targetObject instanceof TextValue) {
                final TextValue target = (TextValue) targetObject;
                target.setValueAt(index - 1, value.toString());
            } else {
                throw new I4GLRuntimeException("Can not assign to a non string variable");
            }
        } catch (FrameSlotTypeException e) {
            throw new UnexpectedRuntimeException();
        }
    }

    @Override
    public boolean hasTag(Class<? extends Tag> tag) {
        return tag == WriteVariableTag.class || super.hasTag(tag);
    }
}
