package org.guillermomolina.i4gl.nodes.variables.write;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.dsl.TypeSystemReference;
import com.oracle.truffle.api.instrumentation.StandardTags.WriteVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;

import org.guillermomolina.i4gl.nodes.expression.I4GLExpressionNode;
import org.guillermomolina.i4gl.nodes.I4GLTypeSystem;
import org.guillermomolina.i4gl.nodes.statement.I4GLStatementNode;
import org.guillermomolina.i4gl.runtime.types.I4GLType;
import org.guillermomolina.i4gl.runtime.types.compound.I4GLCharType;
import org.guillermomolina.i4gl.runtime.types.compound.I4GLTextType;
import org.guillermomolina.i4gl.runtime.types.compound.I4GLVarcharType;
import org.guillermomolina.i4gl.runtime.values.I4GLChar;
import org.guillermomolina.i4gl.runtime.values.I4GLRecord;
import org.guillermomolina.i4gl.runtime.values.I4GLVarchar;

/**
 * Node representing assignment to a record. Compared to
 * {@link I4GLAssignToLocalVariableNode} it assigns the value to the record's frame
 * instead of function's frame.
 *
 * This node uses specializations which means that it is not used directly but
 * completed node is generated by Truffle. {@link AssignToRecordFieldNodeGen}
 */
@NodeChild(value = "recordNode", type = I4GLExpressionNode.class)
@NodeChild(value = "indexNode", type = I4GLExpressionNode.class)
@NodeChild(value = "valueNode", type = I4GLExpressionNode.class)
@TypeSystemReference(I4GLTypeSystem.class)
public abstract class I4GLAssignToRecordTextNode extends I4GLStatementNode {

    private final String identifier;
    private final I4GLType descriptor;

    I4GLAssignToRecordTextNode(String identifier, I4GLType descriptor) {
        this.identifier = identifier;
        this.descriptor = descriptor;
    }

    protected boolean isChar() {
        return descriptor instanceof I4GLCharType;
    }

    @Specialization(guards = "isChar()")
    void assignChar(I4GLRecord record, int index, String value) {
        Object targetObject = record.get(identifier);
        if (!(targetObject instanceof I4GLChar)) {
            targetObject = descriptor.getDefaultValue();
            record.put(identifier, targetObject);
        }

        final I4GLChar target = (I4GLChar) targetObject;
        target.setCharAt(index - 1, value.charAt(0));
    }

    protected boolean isVarchar() {
        return descriptor instanceof I4GLVarcharType;
    }

    @Specialization(guards = "isVarchar()")
    void assignVarchar(I4GLRecord record, int index, String value) {
        Object targetObject = record.get(identifier);
        if (!(targetObject instanceof I4GLVarchar)) {
            targetObject = descriptor.getDefaultValue();
            record.put(identifier, targetObject);
        }

        final I4GLVarchar target = (I4GLVarchar) targetObject;
        target.setCharAt(index - 1, value.charAt(0));
    }

    protected boolean isText() {
        return descriptor instanceof I4GLTextType;
    }

    @Specialization(guards = "isText()")
    void assignText(I4GLRecord record, int index, String value) {
        Object targetObject = record.get(identifier);
        if (!(targetObject instanceof String)) {
            targetObject = "";
        }
        StringBuilder builder = new StringBuilder((String) targetObject);
        builder.setCharAt(index, value.charAt(0));
        record.put(identifier, targetObject);
    }

    @Override
    public boolean hasTag(Class<? extends Tag> tag) {
        return tag == WriteVariableTag.class || super.hasTag(tag);
    }
}
