package org.guillermomolina.i4gl.nodes.variables.write;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.dsl.TypeSystemReference;
import com.oracle.truffle.api.instrumentation.StandardTags.WriteVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;

import org.guillermomolina.i4gl.nodes.I4GLExpressionNode;
import org.guillermomolina.i4gl.nodes.I4GLTypeSystem;
import org.guillermomolina.i4gl.nodes.statement.I4GLStatementNode;
import org.guillermomolina.i4gl.runtime.customvalues.BigIntArrayValue;
import org.guillermomolina.i4gl.runtime.customvalues.DoubleArrayValue;
import org.guillermomolina.i4gl.runtime.customvalues.IntArrayValue;
import org.guillermomolina.i4gl.runtime.customvalues.SmallFloatArrayValue;

/**
 * Node representing assignment to an array. Compared to
 * {@link I4GLSimpleAssignmentNode} it has to receive also index.
 *
 * This node uses specializations which means that it is not used directly but
 * completed node is generated by Truffle. {@link AssignToArrayNodeGen}
 */
@NodeChild(value = "arrayNode", type = I4GLExpressionNode.class)
@NodeChild(value = "indexNode", type = I4GLExpressionNode.class)
@NodeChild(value = "valueNode", type = I4GLExpressionNode.class)
@TypeSystemReference(I4GLTypeSystem.class)
public abstract class I4GLAssignToIndexedNode extends I4GLStatementNode {

    @Specialization
    void assignToIntArray(IntArrayValue array, int index, int value) {
        array.setValueAt(index - 1, value);
    }

    @Specialization
    void assignToBigIntArray(BigIntArrayValue array, int index, long value) {
        array.setValueAt(index - 1, value);
    }

    @Specialization
    void assignToSmallFloatArray(SmallFloatArrayValue array, int index, float value) {
        array.setValueAt(index - 1, value);
    }

    @Specialization
    void assignToDoubleArray(DoubleArrayValue array, int index, double value) {
        array.setValueAt(index - 1, value);
    }

    @Override
    public boolean hasTag(Class<? extends Tag> tag) {
        return tag == WriteVariableTag.class || super.hasTag(tag);
    }

}
