package org.guillermomolina.i4gl.nodes.variables.write;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeChildren;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.instrumentation.StandardTags.WriteVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;

import org.guillermomolina.i4gl.nodes.I4GLExpressionNode;
import org.guillermomolina.i4gl.nodes.statement.I4GLStatementNode;
import org.guillermomolina.i4gl.parser.types.I4GLTypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.BigIntDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.DoubleDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.IntDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.SmallFloatDescriptor;
import org.guillermomolina.i4gl.runtime.customvalues.RecordValue;

/**
 * Node representing assignment to a record. Compared to {@link I4GLSimpleAssignmentNode} it assigns the value to the record's
 * frame instead of function's frame.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link AssignToRecordFieldNodeGen}
 */
@NodeChildren({
        @NodeChild(value = "recordNode", type = I4GLExpressionNode.class),
        @NodeChild(value = "valueNode", type = I4GLExpressionNode.class)
})
public abstract class I4GLAssignToRecordFieldNode extends I4GLStatementNode {

    private final String identifier;
    private final I4GLTypeDescriptor descriptor;

    I4GLAssignToRecordFieldNode(String identifier, I4GLTypeDescriptor descriptor) {
        this.identifier = identifier;
        this.descriptor = descriptor;
    }

    protected boolean isInt() {
        return descriptor == IntDescriptor.SINGLETON;
    }

    @Specialization(guards = "isInt()")
    void assignInt(RecordValue record, int value) {
        record.getFrame().setInt(record.getSlot(this.identifier), value);
    }

    protected boolean isBigInt() {
        return descriptor == BigIntDescriptor.SINGLETON;
    }

    @Specialization(guards = "isBigInt()")
    void assignBigInt(RecordValue record, long value) {
        record.getFrame().setLong(record.getSlot(this.identifier), value);
    }

    protected boolean isSmallFloat() {
        return descriptor == SmallFloatDescriptor.SINGLETON;
    }

    @Specialization(guards = "isSmallFloat()")
    void assignSmallFloat(RecordValue record, float value) {
        record.getFrame().setFloat(record.getSlot(this.identifier), value);
    }

    protected boolean isDouble() {
        return descriptor == DoubleDescriptor.SINGLETON;
    }

    @Specialization(guards = "isDouble()")
    void assignDouble(RecordValue record, double value) {
        record.getFrame().setDouble(record.getSlot(this.identifier), value);
    }

    @Specialization
    void assignGeneric(RecordValue record, Object value) {
        record.getFrame().setObject(record.getSlot(this.identifier), value);
    }

    @Override
    public boolean hasTag(Class<? extends Tag> tag) {
        return tag == WriteVariableTag.class || super.hasTag(tag);
    }
}
