package org.guillermomolina.i4gl.nodes.variables.write;

import java.util.Arrays;

import com.oracle.truffle.api.CompilerDirectives;
import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeField;
import com.oracle.truffle.api.dsl.NodeFields;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.dsl.TypeSystemReference;
import com.oracle.truffle.api.frame.FrameSlot;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.instrumentation.StandardTags.WriteVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;
import com.oracle.truffle.api.nodes.ExplodeLoop;

import org.guillermomolina.i4gl.I4GLTypes;
import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.nodes.statement.I4GLStatementNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.types.compound.TextDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.IntDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.LongDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.RealDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.SmallFloatDescriptor;
import org.guillermomolina.i4gl.runtime.customvalues.NullValue;
import org.guillermomolina.i4gl.runtime.customvalues.RecordValue;
import org.guillermomolina.i4gl.runtime.customvalues.TextValue;
import org.guillermomolina.i4gl.runtime.exceptions.I4GLRuntimeException;
import org.guillermomolina.i4gl.runtime.exceptions.InvalidCastException;

/**
 * Node representing assignment to a variable of primitive type.
 *
 * This node uses specializations which means that it is not used directly but
 * completed node is generated by Truffle. {@link SimpleAssignmentNodeGen}
 */
@NodeFields({ @NodeField(name = "slot", type = FrameSlot.class),
        @NodeField(name = "typeDescriptor", type = TypeDescriptor.class), })
@NodeChild(value = "valueNode", type = ExpressionNode.class)
@TypeSystemReference(I4GLTypes.class)
public abstract class SimpleAssignmentNode extends I4GLStatementNode {

    protected abstract FrameSlot getSlot();

    protected abstract TypeDescriptor getTypeDescriptor();

    @CompilerDirectives.CompilationFinal
    private int jumps = -1;

    protected boolean isInt() {
        return getTypeDescriptor() == IntDescriptor.SINGLETON;
    }

    protected boolean isLong() {
        return getTypeDescriptor() == LongDescriptor.SINGLETON;
    }

    protected boolean isFloat() {
        return getTypeDescriptor() == SmallFloatDescriptor.SINGLETON;
    }

    protected boolean isDouble() {
        return getTypeDescriptor() == RealDescriptor.SINGLETON;
    }

    protected boolean isString() {
        return getTypeDescriptor() instanceof TextDescriptor;
    }

    @Specialization(guards = "isInt()")
    void writeInt(final VirtualFrame frame, final int value) {
        getFrame(frame).setInt(getSlot(), value);
    }

    @Specialization(guards = "isInt()")
    void writeInt(final VirtualFrame frame, final TextValue string) {
        try {
            final int value = Integer.parseInt(string.toString());
            getFrame(frame).setInt(getSlot(), value);
        } catch (final NumberFormatException e) {
            throw new InvalidCastException(string, getTypeDescriptor());
        }
    }

    @Specialization(guards = "isLong()")
    void writeLong(final VirtualFrame frame, final long value) {
        getFrame(frame).setLong(getSlot(), value);
    }

    @Specialization(guards = "isLong()")
    void writeLong(final VirtualFrame frame, final TextValue string) {
        try {
            final long value = Long.parseLong(string.toString());
            getFrame(frame).setLong(getSlot(), value);
        } catch (final NumberFormatException e) {
            throw new InvalidCastException(string, getTypeDescriptor());
        }
    }

    @Specialization(guards = "isFloat()")
    void writeFloat(final VirtualFrame frame, final float value) {
        getFrame(frame).setFloat(getSlot(), value);
    }

    @Specialization(guards = "isFloat()")
    void writeFloat(final VirtualFrame frame, final TextValue string) {
        try {
            final float value = Float.parseFloat(string.toString());
            getFrame(frame).setFloat(getSlot(), value);
        } catch (final NumberFormatException e) {
            throw new InvalidCastException(string, getTypeDescriptor());
        }
    }

    @Specialization(guards = "isDouble()")
    void writeDouble(final VirtualFrame frame, final double value) {
        getFrame(frame).setDouble(getSlot(), value);
    }

    @Specialization(guards = "isDouble()")
    void writeDouble(final VirtualFrame frame, final TextValue string) {
        try {
            final double value = Double.parseDouble(string.toString());
            getFrame(frame).setDouble(getSlot(), value);
        } catch (final NumberFormatException e) {
            throw new InvalidCastException(string, getTypeDescriptor());
        }
    }

    @Specialization
    void assignRecord(final VirtualFrame frame, final RecordValue record) {
        getFrame(frame).setObject(getSlot(), record.getCopy());
    }

    @Specialization(guards = "isString()")
    void assignString(VirtualFrame frame, final TextValue value) {
        frame = getFrame(frame);

        Object targetObject = frame.getValue(getSlot());
        if (targetObject instanceof NullValue) {
            targetObject = getTypeDescriptor().getDefaultValue();
            frame.setObject(getSlot(), targetObject);
        }
        if (targetObject instanceof TextValue) {
            final TextValue target = (TextValue) targetObject;
            target.assignString(value.toString());
        } else {
            throw new I4GLRuntimeException("Can not assign to a non string variable");
        }
    }

    @Specialization
    void assignNull(final VirtualFrame frame, final NullValue value) {
        getFrame(frame).setObject(getSlot(), value);
    }

    @Specialization
    void assignIntArray(final VirtualFrame frame, final int[] array) {
        getFrame(frame).setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    @Specialization
    void assignLongArray(final VirtualFrame frame, final long[] array) {
        getFrame(frame).setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    @Specialization
    void assignFloatArray(final VirtualFrame frame, final float[] array) {
        getFrame(frame).setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    @Specialization
    void assignDoubleArray(final VirtualFrame frame, final double[] array) {
        getFrame(frame).setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    /**
     * This is used for multidimensional arrays
     */
    @Specialization
    void assignArray(final VirtualFrame frame, final Object[] array) {
        getFrame(frame).setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    @Specialization
    void assignArray(final VirtualFrame frame, final TextValue array) {
        getFrame(frame).setObject(getSlot(), array.createDeepCopy());
    }

    @ExplodeLoop
    private VirtualFrame getFrame(VirtualFrame frame) {
        if (jumps == -1) {
            jumps = this.getJumpsToFrame(frame, getSlot());
            CompilerDirectives.transferToInterpreterAndInvalidate();
        }

        for (int i = 0; i < jumps; ++i) {
            frame = (VirtualFrame) frame.getArguments()[0];
        }

        return frame;
    }

    @Override
    public boolean hasTag(final Class<? extends Tag> tag) {
        return tag == WriteVariableTag.class || super.hasTag(tag);
    }
}
