package i4gl.nodes.variables.write;

import java.util.Arrays;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeField;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.dsl.TypeSystemReference;
import com.oracle.truffle.api.frame.FrameSlot;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.instrumentation.StandardTags.WriteVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;

import i4gl.I4GLTypeSystem;
import i4gl.nodes.expression.ExpressionNode;
import i4gl.nodes.statement.StatementNode;
import i4gl.runtime.types.BaseType;
import i4gl.runtime.types.compound.CharType;
import i4gl.runtime.types.compound.DateType;
import i4gl.runtime.types.compound.VarcharType;
import i4gl.runtime.types.primitive.BigIntType;
import i4gl.runtime.types.primitive.FloatType;
import i4gl.runtime.types.primitive.IntType;
import i4gl.runtime.types.primitive.SmallFloatType;
import i4gl.runtime.types.primitive.SmallIntType;
import i4gl.runtime.values.Char;
import i4gl.runtime.values.Date;
import i4gl.runtime.values.Null;
import i4gl.runtime.values.Record;
import i4gl.runtime.values.Varchar;

/**
 * Node representing assignment to a variable of primitive type.
 *
 * This node uses specializations which means that it is not used directly but
 * completed node is generated by Truffle. {@link SimpleAssignmentNodeGen}
 */
@NodeField(name = "slot", type = FrameSlot.class)
@NodeField(name = "type", type = BaseType.class)
@NodeChild(value = "valueNode", type = ExpressionNode.class)
@TypeSystemReference(I4GLTypeSystem.class)
public abstract class AssignToLocalVariableNode extends StatementNode {

    public abstract FrameSlot getSlot();

    protected abstract BaseType getType();
    
    protected boolean isSmallInt() {
        return getType() == SmallIntType.SINGLETON;
    }

    @Specialization(guards = "isSmallInt()")
    void writeSmallInt(final VirtualFrame frame, final short value) {
        frame.setObject(getSlot(), value);
    }

    protected boolean isInt() {
        return getType() == IntType.SINGLETON;
    }

    @Specialization(guards = "isInt()")
    void writeInt(final VirtualFrame frame, final int value) {
        frame.setInt(getSlot(), value);
    }
    
    protected boolean isBigInt() {
        return getType() == BigIntType.SINGLETON;
    }

    @Specialization(guards = "isBigInt()")
    void writeBigInt(final VirtualFrame frame, final long value) {
        frame.setLong(getSlot(), value);
    }

    protected boolean isSmallFloat() {
        return getType() == SmallFloatType.SINGLETON;
    }

    @Specialization(guards = "isSmallFloat()")
    void writeSmallFloat(final VirtualFrame frame, final float value) {
        frame.setFloat(getSlot(), value);
    }

    protected boolean isFloat() {
        return getType() == FloatType.SINGLETON;
    }

    @Specialization(guards = "isFloat()")
    void writeDouble(final VirtualFrame frame, final double value) {
        frame.setDouble(getSlot(), value);
    }

    protected boolean isChar() {
        return getType() instanceof CharType;
    }

    @Specialization(guards = "isChar()")
    void assignChar(final VirtualFrame frame, final String string) {
        Char value = (Char) getType().getDefaultValue();
        value.assignString(string);
        frame.setObject(getSlot(), value);
    }

    protected boolean isVarchar() {
        return getType() instanceof VarcharType;
    }

    @Specialization(guards = "isVarchar()")
    void assignVarchar(final VirtualFrame frame, final String string) {
        Varchar value = (Varchar) getType().getDefaultValue();
        value.assignString(string);
        frame.setObject(getSlot(), value);
    }

    protected boolean isDate() {
        return getType() == DateType.SINGLETON;
    }

    @Specialization(guards = "isDate()")
    void writeDate(final VirtualFrame frame, final int value) {
        frame.setObject(getSlot(), new Date(value));
    }

    @Specialization(guards = "isDate()")
    void writeDate(final VirtualFrame frame, final String value) {
        frame.setObject(getSlot(), new Date(value));
    }

    protected boolean isDateAndValueIsNull(final Object value) {
        return isDate() && value == Null.SINGLETON;
    }

    @Specialization(guards = "isDateAndValueIsNull(value) ")
    void writeDate(final VirtualFrame frame, final Object value) {
        frame.setObject(getSlot(), new Date());
    }

    @Specialization
    void assignRecord(final VirtualFrame frame, final Record record) {
        frame.setObject(getSlot(), record.createDeepCopy());
    }

    @Specialization
    void assignSmallIntArray(final VirtualFrame frame, final short[] array) {
        frame.setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    @Specialization
    void assignIntArray(final VirtualFrame frame, final int[] array) {
        frame.setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    @Specialization
    void assignBigIntArray(final VirtualFrame frame, final long[] array) {
        frame.setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    @Specialization
    void assignSmallFloatArray(final VirtualFrame frame, final float[] array) {
        frame.setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    @Specialization
    void assignDoubleArray(final VirtualFrame frame, final double[] array) {
        frame.setObject(getSlot(), Arrays.copyOf(array, array.length));
    }

    @Specialization
    void assignArray(final VirtualFrame frame, final Object[] array) {
        frame.setObject(getSlot(), Arrays.copyOf(array, array.length));
    }
/*
    @Specialization(replaces = {"writeSmallInt", "writeInt", "writeBigInt", "writeSmallFloat", "writeDouble", "assignChar", "assignVarchar", "assignRecord", "assignSmallIntArray", "assignIntArray", "assignBigIntArray", "assignSmallFloatArray", "assignDoubleArray", "assignArray"})
    void assign(final VirtualFrame frame, final Object value) {
        throw new I4GLRuntimeException("Can not assign an Object to a " + getType());
    }
*/
    @Override
    public boolean hasTag(final Class<? extends Tag> tag) {
        return tag == WriteVariableTag.class || super.hasTag(tag);
    }
}
