package i4gl.nodes.arithmetic;

import com.oracle.truffle.api.CompilerDirectives.TruffleBoundary;
import com.oracle.truffle.api.dsl.Fallback;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import i4gl.nodes.expression.I4GLBinaryExpressionNode;
import i4gl.runtime.exceptions.I4GLRuntimeException;

/**
 * Node representing arithmetic division on numeric arguments.
 *
 * This node uses specializations which means that it is not used directly but
 * completed node is generated by Truffle. {@link I4GLDivideNodeGen}
 */
@NodeInfo(shortName = "/")
public abstract class I4GLDivideNode extends I4GLBinaryExpressionNode {

    @Specialization(rewriteOn = ArithmeticException.class)
    protected int div(int left, int right) {
        int result = left / right;
        /*
         * The division overflows if left is Int.MIN_VALUE and right is -1.
         */
        if ((left & right & result) < 0) {
            throw new ArithmeticException("int overflow");
        }
        return result;
    }

    @Specialization
    @TruffleBoundary
    protected long div(long left, long right) {
        long result = left / right;
        /*
         * The division overflows if left is Long.MIN_VALUE and right is -1.
         */
        if ((left & right & result) < 0) {
            throw new ArithmeticException("long overflow");
        }
        return result;
    }

    @Specialization
    protected float div(float left, float right) {
        return left / right;
    }

    @Specialization
    @TruffleBoundary
    protected double div(double left, double right) {
        return left / right;
    }

    @Fallback
    protected Object typeError(Object left, Object right) {
        throw new I4GLRuntimeException("Type error doing: " + left + " / " + right);
    }
}
