package i4gl.nodes.arithmetic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import i4gl.nodes.expression.BinaryExpressionNode;

/**
 * Node representing modulo operation.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link ModuloNodeGen}
 */
@NodeInfo(shortName = "MOD")
public abstract class ModuloNode extends BinaryExpressionNode {

    @Specialization
    protected short mod(short left, short right) {
        return (short) (left % right);
    }

    @Specialization
    protected int mod(int left, int right) {
        return left % right;
    }

	@Specialization
	protected long mod(long left, long right) {
		return left % right;
	}
}
