package i4gl.nodes.arithmetic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import i4gl.nodes.expression.UnaryNode;

/**
 * Node representing unary negation operation on numeric values.
 *
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link NegationNodeGen}
 */
@NodeInfo(shortName = "NEG")
public abstract class NegationNode extends UnaryNode {

    @Specialization
    short neg(short argument) {
        return (short) -argument;
    }

    @Specialization
    int neg(int argument) {
        return -argument;
    }

	@Specialization
	long neg(long argument) {
		return -argument;
	}

	@Specialization
	float neg(float argument) {
		return -argument;
	}

	@Specialization
	double neg(double argument) {
		return -argument;
	}

}
