package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import org.guillermomolina.i4gl.nodes.I4GLExpressionNode;
import org.guillermomolina.i4gl.runtime.types.I4GLType;
import org.guillermomolina.i4gl.runtime.types.primitive.I4GLBigIntType;

/**
 * Node representing long literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link BigIntLiteralNodeGen}
 */
public abstract class I4GLBigIntLiteralNode extends I4GLExpressionNode {

	private final long value;

	I4GLBigIntLiteralNode(long value) {
		this.value = value;
	}

	@Specialization
	public long execute() {
		return value;
	}

    @Override
    public I4GLType getType() {
        return I4GLBigIntType.SINGLETON;
    }

}
