package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import org.guillermomolina.i4gl.nodes.I4GLExpressionNode;
import org.guillermomolina.i4gl.parser.types.I4GLTypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.DoubleDescriptor;

/**
 * Node representing real literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link I4GLDoubleLiteralNode}
 */
public abstract class I4GLDoubleLiteralNode extends I4GLExpressionNode {

	private final double value;

	I4GLDoubleLiteralNode(double value) {
		this.value = value;
	}

	@Specialization
	public double execute() {
		return value;
	}

    @Override
    public I4GLTypeDescriptor getType() {
        return DoubleDescriptor.SINGLETON;
    }

}
