package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import org.guillermomolina.i4gl.nodes.I4GLExpressionNode;
import org.guillermomolina.i4gl.parser.types.I4GLTypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.IntDescriptor;

/**
 * Node representing integer literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link IntLiteralNodeGen}
 */
public abstract class I4GLIntLiteralNode extends I4GLExpressionNode {

	private final int value;

	I4GLIntLiteralNode(int value) {
		this.value = value;
	}

	@Specialization
	public int execute() {
		return value;
	}

    @Override
    public I4GLTypeDescriptor getType() {
        return IntDescriptor.SINGLETON;
    }

}
