package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.types.compound.TextDescriptor;
import org.guillermomolina.i4gl.runtime.customvalues.I4GLString;

/**
 * Node representing string literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link I4GLStringLiteralNodeGen}
 */
public abstract class I4GLStringLiteralNode extends ExpressionNode {

	private final I4GLString value;

	I4GLStringLiteralNode(String value) {
		this.value = new I4GLString(value);
	}

	@Specialization
	public I4GLString execute() {
		return value;
	}

    @Override
    public TypeDescriptor getType() {
        return TextDescriptor.getInstance();
    }

}
