package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import org.guillermomolina.i4gl.nodes.I4GLExpressionNode;
import org.guillermomolina.i4gl.parser.types.I4GLTypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.SmallFloatDescriptor;

/**
 * Node representing float literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link I4GLDoubleLiteralNode}
 */
public abstract class I4GLSmallFloatLiteralNode extends I4GLExpressionNode {

	private final float value;

	I4GLSmallFloatLiteralNode(float value) {
		this.value = value;
	}

	@Specialization
	public float execute() {
		return value;
	}

    @Override
    public I4GLTypeDescriptor getType() {
        return SmallFloatDescriptor.SINGLETON;
    }

}
