package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.Int8Descriptor;

/**
 * Node representing char literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link CharLiteralNodeGen}
 */
public abstract class Int8LiteralNode extends ExpressionNode {

	private final char value;

	Int8LiteralNode(char value) {
		this.value = value;
	}

	@Specialization
	public char execute() {
		return value;
	}

    @Override
    public TypeDescriptor getType() {
        return Int8Descriptor.getInstance();
    }

}
