package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.IntDescriptor;

/**
 * Node representing integer literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link IntLiteralNodeGen}
 */
public abstract class IntLiteralNode extends ExpressionNode {

	private final int value;

	IntLiteralNode(int value) {
		this.value = value;
	}

	@Specialization
	public int execute() {
		return value;
	}

    @Override
    public TypeDescriptor getType() {
        return IntDescriptor.getInstance();
    }

}
