package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.SmallFloatDescriptor;

/**
 * Node representing float literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link RealLiteralNode}
 */
public abstract class SmallFloatLiteralNode extends ExpressionNode {

	private final float value;

	SmallFloatLiteralNode(float value) {
		this.value = value;
	}

	@Specialization
	public float execute() {
		return value;
	}

    @Override
    public TypeDescriptor getType() {
        return SmallFloatDescriptor.getInstance();
    }

}
