package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;
import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.runtime.customvalues.I4GLSubroutine;
import org.guillermomolina.i4gl.parser.identifierstable.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.identifierstable.types.subroutine.SubroutineDescriptor;

/**
 * Node representing subroutine literal. This is used for example for passing subroutines as a parameter to another subroutine.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link SubroutineLiteralNodeGen}
 */
public abstract class SubroutineLiteralNode extends ExpressionNode {

    private final I4GLSubroutine function;
    private final SubroutineDescriptor descriptor;

    SubroutineLiteralNode(I4GLSubroutine function, SubroutineDescriptor descriptor) {
        this.function = function;
        this.descriptor = descriptor;
    }

    @Specialization
    public I4GLSubroutine execute() {
        return function;
    }

    @Override
    public TypeDescriptor getType() {
        return descriptor;
    }

}
