package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.types.compound.TextDescriptor;
import org.guillermomolina.i4gl.runtime.customvalues.TextValue;

/**
 * Node representing string literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link TextLiteralNodeGen}
 */
public abstract class TextLiteralNode extends ExpressionNode {

	private final TextValue value;

	TextLiteralNode(String value) {
		this.value = new TextValue(value);
	}

	@Specialization
	public TextValue execute() {
		return value;
	}

    @Override
    public TypeDescriptor getType() {
        return TextDescriptor.getInstance();
    }

}
