package org.guillermomolina.i4gl.nodes.literals;

import com.oracle.truffle.api.frame.VirtualFrame;

import org.guillermomolina.i4gl.nodes.ExpressionNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.types.compound.TextDescriptor;

/**
 * Node representing string literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link TextLiteralNodeGen}
 */
public final class TextLiteralNode extends ExpressionNode {

	private final String value;

	public TextLiteralNode(String value) {
		this.value = value;
	}

    @Override
    public String executeGeneric(VirtualFrame frame) {
        return value;
    }

    @Override
    public TypeDescriptor getType() {
        return TextDescriptor.SINGLETON;
    }

}
