package i4gl.nodes.logic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import i4gl.nodes.expression.I4GLBinaryExpressionNode;
import i4gl.runtime.types.I4GLType;
import i4gl.runtime.types.primitive.I4GLIntType;

/**
 * Node representing equals operation.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link EqualsNodeGen}
 */
@NodeInfo(shortName = "=")
public abstract class I4GLEqualsNode extends I4GLBinaryExpressionNode {
    @Specialization
    protected int equals(short left, short right) {
        return left == right ? 1 : 0;
    }
    
    @Specialization
    protected int equals(int left, int right) {
        return left == right ? 1 : 0;
    }

    @Specialization
    protected int equals(long left, long right) {
        return left == right ? 1 : 0;
    }

	@Specialization
    protected int equals(float left, float right) {
	    return left == right ? 1 : 0;
    }

	@Specialization
	protected int equals(double left, double right) {
		return left == right ? 1 : 0;
	}

    @Override
    public I4GLType getType() {
        return I4GLIntType.SINGLETON;
    }

}
