package i4gl.nodes.logic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.NodeInfo;

import i4gl.nodes.expression.I4GLUnaryNode;
import i4gl.runtime.types.BaseType;
import i4gl.runtime.types.primitive.IntType;
import i4gl.runtime.values.I4GLNull;

/**
 * Node representing logical not operation.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link IsNullNodeGen}
 */
@NodeInfo(shortName = "IS NULL")
public abstract class I4GLIsNullNode extends I4GLUnaryNode {

	@Override
	public abstract int executeInt(VirtualFrame frame);

	@Specialization
	int isNull(Object child) {
		return child == I4GLNull.SINGLETON ? 1 : 0;
	}

    @Override
    public BaseType getType() {
        return IntType.SINGLETON;
    }
}
