package i4gl.nodes.logic;

import com.oracle.truffle.api.CompilerDirectives.TruffleBoundary;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import i4gl.nodes.expression.BinaryExpressionNode;
import i4gl.runtime.types.BaseType;
import i4gl.runtime.types.primitive.IntType;

/**
 * Node representing less than or equal operation.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link LessThanOrEqualNodeGen}
 */
@NodeInfo(shortName = "<=")
public abstract class LessThanOrEqualNode extends BinaryExpressionNode {
    @Specialization
    int lessThanOrEqual(short left, short right) {
        return left <= right ? 1 : 0;
    }

    @Specialization
    int lessThanOrEqual(int left, int right) {
        return left <= right ? 1 : 0;
    }

    @Specialization
    @TruffleBoundary
	int lessThanOrEqual(long left, long right) {
		return left <= right ? 1 : 0;
	}

    @Specialization
    @TruffleBoundary
	int lessThanOrEqual(float left, float right) {
		return left <= right ? 1 : 0;
	}

    @Specialization
    @TruffleBoundary
	int lessThanOrEqual(double left, double right) {
		return left <= right ? 1 : 0;
	}

    @Override
    public BaseType getReturnType() {
        return IntType.SINGLETON;
    }

}
