package i4gl.nodes.logic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import i4gl.exceptions.NotImplementedException;
import i4gl.nodes.expression.BinaryExpressionNode;
import i4gl.runtime.types.BaseType;
import i4gl.runtime.types.primitive.IntType;

/**
 * Node representing like operation.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link LikeNodeGen}
 */
@NodeInfo(shortName = "LIKE")
public abstract class LikeNode extends BinaryExpressionNode {

    LikeNode() {
        throw new NotImplementedException();
    }

    @Specialization
    protected int like(int left, int right) {
        return left == right ? 1 : 0;
    }

    @Override
    public BaseType getReturnType() {
        return IntType.SINGLETON;
    }
}
