package i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import i4gl.nodes.expression.ExpressionNode;
import i4gl.runtime.types.BaseType;
import i4gl.runtime.types.primitive.FloatType;

/**
 * Node representing real literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link DoubleLiteralNodeGen}
 */
public abstract class DoubleLiteralNode extends ExpressionNode {

	private final double value;

	DoubleLiteralNode(double value) {
		this.value = value;
	}

	@Specialization
	public double execute() {
		return value;
	}

    @Override
    public BaseType getReturnType() {
        return FloatType.SINGLETON;
    }

}
