package i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import i4gl.nodes.expression.I4GLExpressionNode;
import i4gl.runtime.types.BaseType;
import i4gl.runtime.types.primitive.SmallFloatType;

/**
 * Node representing float literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link I4GLDoubleLiteralNode}
 */
public abstract class I4GLSmallFloatLiteralNode extends I4GLExpressionNode {

	private final float value;

	I4GLSmallFloatLiteralNode(float value) {
		this.value = value;
	}

	@Specialization
	public float execute() {
		return value;
	}

    @Override
    public BaseType getType() {
        return SmallFloatType.SINGLETON;
    }

}
