package i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import i4gl.nodes.expression.I4GLExpressionNode;
import i4gl.runtime.types.BaseType;
import i4gl.runtime.types.primitive.BigIntType;

/**
 * Node representing long literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link BigIntLiteralNodeGen}
 */
public abstract class I4GLBigIntLiteralNode extends I4GLExpressionNode {

	private final long value;

	I4GLBigIntLiteralNode(long value) {
		this.value = value;
	}

	@Specialization
	public long execute() {
		return value;
	}

    @Override
    public BaseType getType() {
        return BigIntType.SINGLETON;
    }

}
