package i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import i4gl.nodes.expression.ExpressionNode;
import i4gl.runtime.types.BaseType;
import i4gl.runtime.types.primitive.IntType;

/**
 * Node representing integer literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link IntLiteralNodeGen}
 */
public abstract class IntLiteralNode extends ExpressionNode {

	private final int value;

	IntLiteralNode(int value) {
		this.value = value;
	}

	@Specialization
	public int execute() {
		return value;
	}

    @Override
    public BaseType getReturnType() {
        return IntType.SINGLETON;
    }

}
