package i4gl.nodes.literals;

import com.oracle.truffle.api.dsl.Specialization;

import i4gl.nodes.expression.ExpressionNode;
import i4gl.runtime.types.BaseType;
import i4gl.runtime.types.primitive.SmallIntType;

/**
 * Node representing short literal.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link SmallIntLiteralNodeGen}
 */
public abstract class SmallIntLiteralNode extends ExpressionNode {

	private final short value;

	SmallIntLiteralNode(short value) {
		this.value = value;
	}

	@Specialization
	public short execute() {
		return value;
	}

    @Override
    public BaseType getType() {
        return SmallIntType.SINGLETON;
    }

}
