package org.guillermomolina.i4gl.nodes.call;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeField;
import com.oracle.truffle.api.dsl.NodeFields;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.instrumentation.StandardTags.ReadVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;

import org.guillermomolina.i4gl.nodes.I4GLExpressionNode;
import org.guillermomolina.i4gl.nodes.variables.read.I4GLReadFromRecordNodeGen;
import org.guillermomolina.i4gl.parser.types.I4GLTypeDescriptor;
import org.guillermomolina.i4gl.runtime.customvalues.ReturnValue;

/**
 * This node reads value from an valuenode with specified identifier.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link I4GLReadFromRecordNodeGen}
 */
@NodeChild(value = "valuenode", type = I4GLExpressionNode.class)
@NodeFields({
    @NodeField(name = "index", type = Integer.class),
    @NodeField(name = "returnType", type = I4GLTypeDescriptor.class)
})
public abstract class I4GLReadFromReturnNode extends I4GLExpressionNode {

    protected abstract I4GLTypeDescriptor getReturnType();

    protected abstract int getIndex();

    @Specialization(guards = "isInt()")
    int readInt(ReturnValue valuenode) {
        return valuenode.getIntAt(getIndex());
    }

    @Specialization(guards = "isBigInt()")
    long readBigInt(ReturnValue valuenode) {
        return valuenode.getBigIntAt(getIndex());
    }

    @Specialization(guards = "isSmallFloat()")
    float readSmallFloat(ReturnValue valuenode) {
        return valuenode.getSmallFloatAt(getIndex());
    }

    @Specialization(guards = "isFloat()")
    double readFloat(ReturnValue valuenode) {
        return valuenode.getFloatAt(getIndex());
    }

    @Specialization
    Object readGeneric(ReturnValue valuenode) {
        return valuenode.getValueAt(getIndex());
    }

    @Override
    public I4GLTypeDescriptor getType() {
        return this.getReturnType();
    }

    @Override
    public boolean hasTag(Class<? extends Tag> tag) {
        return tag == ReadVariableTag.class || super.hasTag(tag);
    }
}
