package org.guillermomolina.i4gl.nodes.call;

import com.oracle.truffle.api.dsl.NodeChild;
import com.oracle.truffle.api.dsl.NodeField;
import com.oracle.truffle.api.dsl.NodeFields;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.instrumentation.StandardTags.ReadVariableTag;
import com.oracle.truffle.api.instrumentation.Tag;

import org.guillermomolina.i4gl.nodes.I4GLExpressionNode;
import org.guillermomolina.i4gl.nodes.variables.read.I4GLReadFromRecordNodeGen;
import org.guillermomolina.i4gl.parser.types.I4GLTypeDescriptor;

/**
 * This node reads value from an valuenode with specified identifier.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link I4GLReadFromRecordNodeGen}
 */
@NodeChild(value = "valuenode", type = I4GLExpressionNode.class)
@NodeFields({
    @NodeField(name = "index", type = Integer.class),
    @NodeField(name = "returnType", type = I4GLTypeDescriptor.class)
})
public abstract class I4GLReadFromReturnNode extends I4GLExpressionNode {

    protected abstract I4GLTypeDescriptor getReturnType();

    protected abstract int getIndex();

    @Specialization(guards = "isInt()")
    int readInt(Object[] valuenode) {
        return (int) valuenode[getIndex()];
    }

    @Specialization(guards = "isBigInt()")
    long readBigInt(Object[] valuenode) {
        return (long) valuenode[getIndex()];
    }

    @Specialization(guards = "isSmallFloat()")
    float readSmallFloat(Object[] valuenode) {
        return (float) valuenode[getIndex()];
    }

    @Specialization(guards = "isFloat()")
    double readFloat(Object[] valuenode) {
        return (double) valuenode[getIndex()];
    }

    @Specialization
    Object readGeneric(Object[] valuenode) {
        return valuenode[getIndex()];
    }

    @Override
    public I4GLTypeDescriptor getType() {
        return this.getReturnType();
    }

    @Override
    public boolean hasTag(Class<? extends Tag> tag) {
        return tag == ReadVariableTag.class || super.hasTag(tag);
    }
}
