package org.guillermomolina.i4gl.nodes.logic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import org.guillermomolina.i4gl.nodes.I4GLBinaryExpressionNode;
import org.guillermomolina.i4gl.parser.types.I4GLTypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.IntDescriptor;

/**
 * Node representing logical or operation.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link OrNodeGen}
 */
@NodeInfo(shortName = "or")
public abstract class I4GLOrNode extends I4GLBinaryExpressionNode {
    @Specialization
    int or(int left, int right) {
        return (left != 0 || right != 0) ? 1 : 0;
    }

	@Specialization
	int or(long left, long right) {
		return (left != 0 || right != 0) ? 1 : 0;
	}

	@Specialization
	int or(float left, float right) {
		return (left != '0' || right != '0') ? 1 : 0;
	}

	@Specialization
	int or(double left, double right) {
		return (left != 0 || right != 0) ? 1 : 0;
	}

    @Override
    public I4GLTypeDescriptor getType() {
        return IntDescriptor.SINGLETON;
    }

}
