package org.guillermomolina.i4gl.nodes.logic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.NodeInfo;

import org.guillermomolina.i4gl.nodes.arithmetic.UnaryNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.IntDescriptor;
import org.guillermomolina.i4gl.runtime.customvalues.NullValue;

/**
 * Node representing logical not operation.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link IsNullNodeGen}
 */
@NodeInfo(shortName = "IS NULL")
public abstract class IsNullNode extends UnaryNode {

	@Override
	public abstract int executeInt(VirtualFrame frame);

	@Specialization
	int isNull(Object child) {
		return child == NullValue.SINGLETON ? 1 : 0;
	}

    @Override
    public TypeDescriptor getType() {
        return IntDescriptor.SINGLETON;
    }
}
