package org.guillermomolina.i4gl.nodes.logic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import org.guillermomolina.i4gl.exceptions.NotImplementedException;
import org.guillermomolina.i4gl.nodes.BinaryExpressionNode;
import org.guillermomolina.i4gl.parser.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.types.primitive.IntDescriptor;

/**
 * Node representing like operation.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link LikeNodeGen}
 */
@NodeInfo(shortName = "LIKE")
public abstract class LikeNode extends BinaryExpressionNode {

    LikeNode() {
        throw new NotImplementedException();
    }

    @Specialization
    protected int like(int left, int right) {
        return left == right ? 1 : 0;
    }

    @Override
    public TypeDescriptor getType() {
        return IntDescriptor.SINGLETON;
    }
}
