package org.guillermomolina.i4gl.nodes.logic;

import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.nodes.NodeInfo;

import org.guillermomolina.i4gl.exceptions.NotImplementedException;
import org.guillermomolina.i4gl.nodes.BinaryExpressionNode;
import org.guillermomolina.i4gl.parser.identifierstable.types.TypeDescriptor;
import org.guillermomolina.i4gl.parser.identifierstable.types.primitive.IntDescriptor;

/**
 * Node representing matches operation.
 *
 * This node uses specializations which means that it is not used directly but completed node is generated by Truffle.
 * {@link MatchesNodeGen}
 */
@NodeInfo(shortName = "MATCHES")
public abstract class MatchesNode extends BinaryExpressionNode {

    MatchesNode() {
        throw new NotImplementedException();
    }

    @Specialization
    protected int matches(int left, int right) {
        return left == right ? 1 : 0;
    }

    @Override
    public TypeDescriptor getType() {
        return IntDescriptor.getInstance();
    }
}
